# -*- coding: utf-8 -*-
"""Classification_with_Naive_Bayes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N_S7ApQX04mK3nbX9L4EGWpYXTX1nRdu

## Naive Bayes' Classification

## Import the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Read the dataset"""

dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ai/master/storepurchasedata.csv')

"""## Separate out the independent and dependent variable"""

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

"""## Train Test Split"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

"""## Feature Scaling"""

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

"""## Build and train a Naive Bayes' Classification model

We weill build Gaussian naive Bayes model using the Scikit Learn Library
"""

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

"""## Confusion Matrix and Accuracy"""

y_pred = classifier.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
cm

print(accuracy_score(y_test,y_pred))

