# -*- coding: utf-8 -*-
"""colabdemo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dI3nfVKYclvUcPgn2y79AWRH1b7Zbt60
"""

import numpy as np

import tensorflow as tf

3-4

3+4

!pip install pydot



# This is also a comment
3+40

"""This is a comment"""

