# -*- coding: utf-8 -*-
"""Decision_Tree_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SiXs4rThmOa7Pf4qvkVg8Ps9VhTmmQUa

## Decision Tree Regression

## Import the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Read the dataset and check sample records"""

dataset = pd.read_csv('https://raw.githubusercontent.com/futurexskill/ai/master/automilespergallon.csv')
dataset.head()

"""## Get Dataset information"""

print(dataset.info())

"""## Separate out the independent and dependent variables

### X will contain displacement, horsepower,	weight,	acceleration
"""

X = dataset.iloc[:, 1:-1].values

X[0]

"""### y will contain milespergallon"""

y = dataset.iloc[:, -1].values

"""## Exploratory Data Analysis using MatplotLib

### Plot displacement vs milespergallon
"""

plt.scatter(X[:,0],y)

"""### Plot horsepower vs milespergallon"""

plt.scatter(X[:,1],y)

"""### Plot weight vs milespergallon"""

plt.scatter(X[:,2],y)

"""### Plot acceleration vs milespergallon"""

plt.scatter(X[:,3],y)

"""## Split the Training and Test Data"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state=0)

"""## Build a Decision Tree Regression model"""

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)

"""Train the model. This step is Machine Learning.  Machine is learning from training data"""

regressor.fit(X_train, y_train)

"""## Evaluate the model"""

rsqaured = regressor.score(X_test, y_test)
rsqaured

"""## Predict output for the test set"""

y_pred = regressor.predict(X_test)
y_pred

"""Compare with actual data"""

y_test

"""## Predict for new data"""

y_new_pred_sample = regressor.predict(np.array([[200,100,3000,15]]))

y_new_pred_sample

